Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Htest.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using Htest.Data;

namespace Htest.Controllers
{
    public class StudentClassesDTO{
        public List<HClass> classes {get;set;}
        public List<Student> students{get;set;}
        public HClass SelectedClass{get;set;}
    }

    public class TeacherSubmitDTO{
        public string ClassRef{get;set;}
        //public string Teacher{get;set;}

    }

    public class TeacherController : Controller
    {

       [HttpPost]

        public IActionResult saveaward(int Id, string type)
        {
            if (type != null){
                return Ok();
            }
            else{
                return NotFound();
            }
            
        }


        string teacherName = @"Adrian Blacker"; 
        //string className = @"7RED/Ar";

        [HttpGet]
        public IActionResult Index()
        {
            var helper = new ExcelHelper();
            var SClassDTO = new StudentClassesDTO();
            List<HClass> classes = helper.GetAllClassesForTeacher(teacherName);
            SClassDTO.classes = classes;
            
            SClassDTO.SelectedClass = classes[0];
            List<Student> students = helper.GetStudentsForClass(SClassDTO.SelectedClass.Name);
            SClassDTO.students = students;
            return View(SClassDTO);

        }     
        

        [HttpPost]
        public IActionResult Index(TeacherSubmitDTO data){
            var SClassDTO = new StudentClassesDTO();
            var helper = new ExcelHelper();
            List<HClass> classes = helper.GetAllClassesForTeacher(teacherName); //sub out data.Teacher for teacherName if you want hard-coded value
            List<Student> students = helper.GetStudentsForClass(data.ClassRef);
            SClassDTO.classes = classes;
            SClassDTO.students = students;
            return View(SClassDTO);
        }
         
        [HttpGet]
        public IActionResult Upload(string id="")
        {
             ViewBag.Success = TempData["success"];
            // if (!String.IsNullOrEmpty(id)) {
            //     ViewBag.Success = "success";
            // }

            return View((Object)id);
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile xlsfile)
        {
            var fileName = xlsfile.FileName;
            if (System.IO.File.Exists(fileName)) {
                //System.IO.File.Delete(fileName);
            }
            System.IO.File.Delete("test.xlsx");
            using (FileStream output = System.IO.File.Create("text.xlsx"))
            {
                await xlsfile.CopyToAsync(output);
            }
            var cmd=@"xlsxparser.py";
            var args = "\"" + fileName + "\"";
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "python.exe ";
            start.Arguments = string.Format("{0} {1}", cmd, args);
            start.UseShellExecute = false;
            start.RedirectStandardOutput = true;
            Process.Start(start);
            // using(Process process = Process.Start(start))
            // {
            //     using(StreamReader reader = process.StandardOutput)
            //     {
            //         string result = reader.ReadToEnd();
            //         Console.Write(result);
            //     }
            // }
            // ViewBag.Success = "success";    
            return View();
  
        }
        public class HookData {
            public string status {get; set;}
        }
        [HttpPost]
        public IActionResult UploadHook(string name)
        {
            // ViewBag.Success = "Success";
            // TempData["success"] = "success";
            //return RedirectToAction("Upload", "Teacher", new {id=name});
            //return View("/Home/Index");
            return Ok();
        }  
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hildegard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://kit.fontawesome.com/dd67ebef50.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Htest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Students">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Classes</a>
                        </li>
                   
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Htest - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>